In [2]:
import pandas as pd
import numpy as np

In [3]:
retail = pd.read_csv('Retail_Dataset_Modified.csv')

In [4]:
retail.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,BX_PUNE_034,BrandX_India Superstore Pune,BrandX_India,Flagship,Pune,Tier1,Green Tea 100g,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57,1,2022,Q1,Spring
1,BX_MUMBAI_023,BrandX_India Superstore Mumbai,BrandX_India,Street Store,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99,1,2022,Q1,Spring
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring

In [5]:
retail.tail()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5167,BX_MUMBAI_067,BrandX_India Daily Mumbai,BrandX_India,Express,Mumbai,Metro,White Sugar 1kg,Groceries,Sugar,Growing,...,81.6,82.0,Competitive,Low,7.0,136,7,2023,Q3,Monsoon
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon

In [6]:
print(retail.describe())

          Unit_Price     Cost_Price  Profit_Margin  Average_Order_Value  \
count    5171.000000    5171.000000    5171.000000          5171.000000
mean    36147.283117   28008.718236      22.455080         45000.251789
std     53910.395954   41848.286241       4.349469         67405.809814
min        36.000000      28.000000      14.680000            41.000000
25%      2016.500000    1548.500000      18.675000          2476.000000
50%     11816.000000    9136.000000      22.450000         14734.000000
75%     53778.500000   41569.000000      26.235000         66630.000000
max    307651.000000  252171.000000      30.430000        450890.000000

       Inventory_Turnover  Days_of_Stock  Promotion_Impact  \
count         5171.000000    5171.000000       5171.000000
mean             3.928517     142.718816         20.979791
std              2.284159     128.281114         12.212204
min              0.300000      32.000000          0.000000
25%              2.220000      68.000000         13.100000
50%              3.440000     105.000000         22.300000
75%              5.260000     162.000000         31.200000
max             11.100000    1200.000000         40.000000

       Max_Discount_Offered  Return_Rate  Customer_Satisfaction  ...  \
count           5171.000000  5171.000000            5094.000000  ...
mean              22.679172     4.018294               4.209109  ...
std               15.784690     2.292903               0.280465  ...
min                0.000000     0.000000               3.600000  ...
25%                9.000000     2.000000               4.000000  ...
50%               22.000000     4.100000               4.200000  ...
75%               36.000000     6.000000               4.400000  ...
max               50.000000     8.000000               4.900000  ...

       Review_Count  Sales_Rep_Experience  Sales_Rep_Rating  Market_Share  \
count   5171.000000           5171.000000       5171.000000   5171.000000
mean     256.498936              5.548250          4.248018     15.406556
std      140.948535              2.861696          0.433274      6.009766
min       10.000000              1.000000          3.500000      3.000000
25%      138.000000              3.000000          3.900000     11.300000
50%      256.000000              6.000000          4.200000     14.900000
75%      378.000000              8.000000          4.600000     18.900000
max      500.000000             10.000000          5.000000     30.000000

       Competitor_Count  Brand_Loyalty  Brand_Awareness  Delivery_Time  \
count       5171.000000    5171.000000      5171.000000    5111.000000
mean          16.231483      81.351228        80.307097       3.984934
std            6.646939       8.018098         8.542352       2.021598
min            3.000000      67.000000        60.000000       1.000000
25%           11.000000      75.900000        77.700000       2.000000
50%           18.000000      80.400000        83.000000       4.000000
75%           22.000000      84.600000        86.600000       6.000000
max           25.000000     100.000000        90.000000       7.000000

             Month         Year
count  5171.000000  5171.000000
mean      6.567588  2023.016438
std       3.463351     0.814235
min       1.000000  2022.000000
25%       4.000000  2022.000000
50%       7.000000  2023.000000
75%      10.000000  2024.000000
max      12.000000  2024.000000

[8 rows x 21 columns]

In [7]:
print(retail.isnull().sum())

Store_ID                  0
Store_Name                0
Brand_Name                0
Store_Type                0
City                     62
City_Tier                 0
Product_Name             73
Category                  0
Sub_Category              0
Product_Stage             0
Quantity_Available        0
Units_Sold                0
Unit_Price                0
Cost_Price                0
Revenue                  72
Profit_Margin             0
Average_Order_Value       0
Inventory_Turnover        0
Days_of_Stock             0
Customer_Segment          0
Sales_Channel             0
Payment_Method            0
Supplier                 68
Supplier_Rating           0
Promotion_Type            0
Promotion_Impact          0
Max_Discount_Offered      0
Return_Rate               0
Return_Reason             0
Customer_Satisfaction    77
Online_Rating             0
Review_Count              0
Sales_Rep_Experience      0
Sales_Rep_Rating          0
Market_Share              0
Competition_Level         0
Competitor_Count          0
Brand_Loyalty             0
Brand_Awareness           0
Price_Competitiveness     0
Weather_Impact            0
Delivery_Time            60
Shipping_Cost             0
Month                     0
Year                      0
Quarter                   0
Season                    0
dtype: int64

In [8]:
print(retail['Category'].unique())

<StringArray>
[          'Groceries',             'Clothes',             'Gadgets',
         'Electronics',     'Home Appliances',         'ELECTRONICS',
       '  Groceries  ',     'home appliances',     'HOME APPLIANCES',
     '  Electronics  ',             'gadgets',           'groceries',
         'electronics', '  Home Appliances  ',             'clothes',
         '  Gadgets  ',           'GROCERIES',         '  Clothes  ',
             'GADGETS',             'CLOTHES']
Length: 20, dtype: str

In [9]:
selected_columns = retail[['Revenue',
                        'Units_Sold',
                        'Profit_Margin']]

print(selected_columns.head())

   Revenue Units_Sold  Profit_Margin
0     7320         24          21.64
1     1645         35          29.79
2    66340         31          19.86
3    77748         22          18.11
4  1976364         39          20.15

In [10]:
print(retail.iloc[0:2])

        Store_ID                      Store_Name    Brand_Name    Store_Type  \
0    BX_PUNE_034    BrandX_India Superstore Pune  BrandX_India      Flagship
1  BX_MUMBAI_023  BrandX_India Superstore Mumbai  BrandX_India  Street Store

     City City_Tier     Product_Name   Category Sub_Category Product_Stage  \
0    Pune     Tier1   Green Tea 100g  Groceries          Tea     Declining
1  Mumbai     Metro  White Sugar 1kg  Groceries        Sugar     Declining

   ... Brand_Loyalty Brand_Awareness  Price_Competitiveness  Weather_Impact  \
0  ...          70.8            75.7               Standard             Low
1  ...          80.5            81.5            Competitive             Low

  Delivery_Time  Shipping_Cost  Month  Year  Quarter  Season
0           6.0             57      1  2022       Q1  Spring
1           4.0             99      1  2022       Q1  Spring

[2 rows x 47 columns]

In [12]:
unit_price = retail[retail['Unit_Price']>1000]
unit_price[['Store_Name','Brand_Name']].head()

                        Store_Name    Brand_Name
2         BrandX_India Trends Pune  BrandX_India
3      BrandX_India Trends Chennai  BrandX_India
4     BrandX_India Connect Chennai  BrandX_India
6  BrandX_India Accessories Mumbai  BrandX_India
7       BrandX_India Digital Delhi  BrandX_India

In [13]:
unit_price

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
2,BX_PUNE_073,BrandX_India Trends Pune,BrandX_India,Flagship,Pune,Tier1,Levi's T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101,1,2022,Q1,Spring
3,BX_CHENNAI_061,BrandX_India Trends Chennai,BrandX_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79,1,2022,Q1,Spring
4,BX_CHENNAI_033,BrandX_India Connect Chennai,BrandX_India,Mall Store,Chennai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110,1,2022,Q1,Spring
6,BX_MUMBAI_062,BrandX_India Accessories Mumbai,BrandX_India,Street Store,Mumbai,Metro,PlayStation 5,Gadgets,Gaming Consoles,Mature,...,98.0,81.6,Competitive,Low,2.0,90,1,2022,Q1,Spring
7,BX_DELHI_062,BrandX_India Digital Delhi,BrandX_India,Mall Store,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Mature,...,81.6,82.4,Competitive,Low,3.0,137,1,2022,Q1,Spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5164,BX_MUMBAI_020,BrandX_India Gadget Zone Mumbai,BrandX_India,Street Store,Mumbai,Metro,LG OLED 55Inch,Electronics,Smart TVs,Declining,...,79.6,88.4,Competitive,Low,1.0,101,8,2024,Q3,Monsoon
5166,BX_JAIPUR_077,BrandX_India Style Jaipur,BrandX_India,Street Store,Jaipur,Tier2,Pepe Jeans,Clothes,Jeans,Declining,...,91.3,68.7,Standard,Medium,3.0,150,11,2024,Q4,Winter
5168,BX_KANPUR_097,BrandX_India Gadget Zone Kanpur,BrandX_India,Flagship,Kanpur,Tier2,Dell XPS 13,Electronics,Laptops,Discontinued,...,89.9,68.1,Standard,Low,1.0,222,7,2023,Q3,Monsoon
5169,BX_MUMBAI_031,BrandX_India Style Mumbai,BrandX_India,Street Store,Mumbai,Metro,Nike Air Max,Clothes,Shoes,Mature,...,80.6,86.5,Competitive,Medium,3.0,138,12,2022,Q4,Winter
5170,BX_DELHI_032,BrandX_India Electronics Delhi,BrandX_India,Flagship,Delhi,Metro,MacBook Air M2,Electronics,Laptops,Declining,...,91.8,85.0,Competitive,Low,3.0,210,6,2024,Q2,Monsoon