In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('Retail_Dataset_Cleaned.csv')

In [3]:
df.head()

,Store_ID,Store_Name,Brand_Name,Store_Type,City,City_Tier,Product_Name,Category,Sub_Category,Product_Stage,...,Brand_Loyalty,Brand_Awareness,Price_Competitiveness,Weather_Impact,Delivery_Time,Shipping_Cost,Month,Year,Quarter,Season
0,Bx_Pune_034,Brandx_India Superstore Pune,Brandx_India,Flagship,Pune,Tier1,Green Tea 100G,Groceries,Tea,Declining,...,70.8,75.7,Standard,Low,6.0,57.0,1,2022,Q1,Spring
1,Bx_Mumbai_023,Brandx_India Superstore Mumbai,Brandx_India,Street Store,Mumbai,Metro,White Sugar 1Kg,Groceries,Sugar,Declining,...,80.5,81.5,Competitive,Low,4.0,99.0,1,2022,Q1,Spring
2,Bx_Pune_073,Brandx_India Trends Pune,Brandx_India,Flagship,Pune,Tier1,Levi'S T-Shirt,Clothes,T-Shirts,Declining,...,68.5,76.7,Standard,Medium,4.0,101.0,1,2022,Q1,Spring
3,Bx_Chennai_061,Brandx_India Trends Chennai,Brandx_India,Mall Store,Chennai,Metro,Adidas Hoodie,Clothes,Jackets,New Launch,...,92.4,88.0,Competitive,Medium,5.0,79.0,1,2022,Q1,Spring
4,Bx_Chennai_033,Brandx_India Connect Chennai,Brandx_India,Mall Store,Chennai,Metro,Playstation 5,Gadgets,Gaming Consoles,Declining,...,82.9,89.5,Competitive,Low,2.0,110.0,1,2022,Q1,Spring

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5146 entries, 0 to 5145
Data columns (total 47 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Store_ID               5146 non-null   str
 1   Store_Name             5146 non-null   str
 2   Brand_Name             5146 non-null   str
 3   Store_Type             5146 non-null   str
 4   City                   5146 non-null   str
 5   City_Tier              5146 non-null   str
 6   Product_Name           5146 non-null   str
 7   Category               5146 non-null   str
 8   Sub_Category           5146 non-null   str
 9   Product_Stage          5146 non-null   str
 10  Quantity_Available     5146 non-null   float64
 11  Units_Sold             5146 non-null   float64
 12  Unit_Price             5146 non-null   int64
 13  Cost_Price             5146 non-null   int64
 14  Revenue                5146 non-null   float64
 15  Profit_Margin          5146 non-null   float64
 16  Average_Order_Value    5146 non-null   int64
 17  Inventory_Turnover     5146 non-null   float64
 18  Days_of_Stock          5146 non-null   int64
 19  Customer_Segment       5146 non-null   str
 20  Sales_Channel          5146 non-null   str
 21  Payment_Method         5146 non-null   str
 22  Supplier               5146 non-null   str
 23  Supplier_Rating        5146 non-null   str
 24  Promotion_Type         5146 non-null   str
 25  Promotion_Impact       5146 non-null   float64
 26  Max_Discount_Offered   5146 non-null   int64
 27  Return_Rate            5146 non-null   float64
 28  Return_Reason          5146 non-null   str
 29  Customer_Satisfaction  5146 non-null   float64
 30  Online_Rating          5146 non-null   float64
 31  Review_Count           5146 non-null   int64
 32  Sales_Rep_Experience   5146 non-null   int64
 33  Sales_Rep_Rating       5146 non-null   float64
 34  Market_Share           5146 non-null   float64
 35  Competition_Level      5146 non-null   str
 36  Competitor_Count       5146 non-null   int64
 37  Brand_Loyalty          5146 non-null   float64
 38  Brand_Awareness        5146 non-null   float64
 39  Price_Competitiveness  5146 non-null   str
 40  Weather_Impact         5146 non-null   str
 41  Delivery_Time          5146 non-null   float64
 42  Shipping_Cost          5146 non-null   float64
 43  Month                  5146 non-null   int64
 44  Year                   5146 non-null   int64
 45  Quarter                5146 non-null   str
 46  Season                 5146 non-null   str
dtypes: float64(15), int64(10), str(22)
memory usage: 1.8 MB

In [6]:
df["Profit_Amount"] = (
    df["Revenue"] *
    df["Profit_Margin"] / 100
)

df[["Revenue",
    "Profit_Margin",
    "Profit_Amount"]].sample(5)

        Revenue  Profit_Margin  Profit_Amount
230     35154.0          17.56   6.173042e+03
155     35056.0          23.20   8.132992e+03
4827   460790.0          29.43   1.356105e+05
869     14150.0          26.50   3.749750e+03
327   3983128.0          29.33   1.168251e+06

In [5]:
df['Profit Amount'] = df['Revenue']*df['Profit_Margin']/100
df[['Store_ID','Store_Name','Profit Amount']].sample(5)

              Store_ID                          Store_Name  Profit Amount
419   Bx_Ahmedabad_043  Brandx_India Accessories Ahmedabad   3.473187e+05
4744      Bx_Delhi_069            Brandx_India Style Delhi   5.815225e+04
3479    Bx_Chennai_098    Brandx_India Accessories Chennai   2.025732e+05
916     Bx_Chennai_034         Brandx_India Trends Chennai   6.495773e+03
2498  Bx_Hyderabad_010      Brandx_India Digital Hyderabad   1.277473e+06

In [7]:
df["Stock_Difference"] = (
    df["Quantity_Available"] -
    df["Units_Sold"]
)

df[["Quantity_Available",
    "Units_Sold",
    "Stock_Difference"]].sample(5)

      Quantity_Available  Units_Sold  Stock_Difference
3689               203.0        46.0             157.0
3318               215.0        78.0             137.0
3288               248.0        78.0             170.0
1519                94.0        16.0              78.0
1125               225.0        39.0             186.0

In [8]:
df["Inventory_Status"] = np.where(
    df["Quantity_Available"] < 100,
    "Low Stock",
    np.where(
        df["Quantity_Available"] <= 200,
        "Medium Stock",
        "High Stock"
    )
)

df[["Quantity_Available",
    "Inventory_Status"]].sample(5)

      Quantity_Available Inventory_Status
2509                95.0        Low Stock
3718               172.0     Medium Stock
2280               133.0     Medium Stock
4192               212.0       High Stock
79                 247.0       High Stock

In [9]:
df["Revenue_Per_Unit"] = (
    df["Revenue"] /
    df["Units_Sold"]
)

df[["Revenue",
    "Units_Sold",
    "Revenue_Per_Unit"]].sample(5)

        Revenue  Units_Sold  Revenue_Per_Unit
4143  3167905.0        65.0           48737.0
1091   135090.0        45.0            3002.0
1407  1644640.0        38.0           43280.0
2391    14740.0        55.0             268.0
3736    36882.0         9.0            4098.0

In [10]:
print(df[[
    "Profit_Amount",
    "Stock_Difference",
    "Inventory_Status",
    "Revenue_Per_Unit"
]].head())

   Profit_Amount  Stock_Difference Inventory_Status  Revenue_Per_Unit
0      1584.0480             101.0     Medium Stock             305.0
1       490.0455             100.0     Medium Stock              47.0
2     13175.1240             184.0       High Stock            2140.0
3     14080.1628             141.0     Medium Stock            3534.0
4    398237.3460             128.0     Medium Stock           50676.0

In [11]:
df["Revenue_Category"] = np.where(
    df["Revenue"] < 5000,
    "Low Revenue",
    np.where(
        df["Revenue"] < 10000,
        "Medium Revenue",
        "High Revenue"
    )
)

df[["Revenue", "Revenue_Category"]].head()

     Revenue Revenue_Category
0     7320.0   Medium Revenue
1     1645.0      Low Revenue
2    66340.0     High Revenue
3    77748.0     High Revenue
4  1976364.0     High Revenue

In [14]:
df["Customer_Feedback"] = np.where(
    df["Customer_Satisfaction"] >= 4,
    "Satisfied",
    "Needs Improvement")
 
df[[
    "Customer_Satisfaction",
    "Customer_Feedback"
]].head()


df[["Customer_Satisfaction", "Customer_Feedback"]].head()

   Customer_Satisfaction  Customer_Feedback
0                    4.0          Satisfied
1                    3.9  Needs Improvement
2                    4.3          Satisfied
3                    4.4          Satisfied
4                    3.9  Needs Improvement

In [15]:
df["Discount_Category"] = np.where(
    df["Max_Discount_Offered"] < 10,
    "Low Discount",
    np.where(
        df["Max_Discount_Offered"] < 20,
        "Medium Discount",
        "High Discount"
    )
)

df[["Max_Discount_Offered", "Discount_Category"]].sample(5)

      Max_Discount_Offered Discount_Category
27                      13   Medium Discount
1265                     7      Low Discount
1795                     0      Low Discount
1567                    18   Medium Discount
1224                    10   Medium Discount

In [16]:
df["Delivery_Speed"] = np.where(
    df["Delivery_Time"] <= 5,
    "Fast Delivery",
    "Standard Delivery"
)

df[[
    "Delivery_Time",
    "Delivery_Speed"
]].head()

   Delivery_Time     Delivery_Speed
0            6.0  Standard Delivery
1            4.0      Fast Delivery
2            4.0      Fast Delivery
3            5.0      Fast Delivery
4            2.0      Fast Delivery